services:
  ultraviolet:
    ports:
      - 8080:8080
    build:
      context: .
    container_name: ultraviolet
    restart: unless-stopped
    volumes:
      - strato_logs:/app/logs

volumes:
  strato_logs:

networks:
  default:
    name: ultraviolet
