/**
 * STRATO Mega Catalog Expander
 * Run: node mega-games.mjs
 * Adds ~500 games via external URLs (go through proxy) + neal.fun tools
 */
import fs from "fs";

const GAMES_JSON = "./public/assets/games.json";
const existing = JSON.parse(fs.readFileSync(GAMES_JSON, "utf8"));
const existingIds = new Set(existing.map(g => g.id));

const g = (id, name, category, url, desc, tags = [], tier = 2) => ({
  id, name, category,
  url: url.startsWith("http") ? url : `/games/${id}/index.html`,
  thumbnail: `/assets/thumbnails/${id}.webp`,
  tier,
  reliability: tier === 1 ? "green" : "yellow",
  description: desc,
  tags
});

const MEGA_GAMES = [
  // ── Neal.fun ─────────────────────────────────────────────────────────────
  g("neal-spend", "Spend Bill Gates Money", "casual", "https://neal.fun/spend/", "Spend 100 billion dollars", ["neal", "money", "fun"], 1),
  g("neal-password", "Password Game", "puzzle", "https://neal.fun/password-game/", "The most brutal password rules", ["neal", "password", "hard"], 1),
  g("neal-absurd-trolley", "Absurd Trolley Problems", "casual", "https://neal.fun/absurd-trolley-problems/", "Moral dilemmas taken to extremes", ["neal", "choices", "funny"], 1),
  g("neal-draw-solar", "Draw a Perfect Circle", "casual", "https://neal.fun/perfect-circle/", "Can you draw a perfect circle?", ["neal", "draw", "skill"], 1),
  g("neal-deep-sea", "The Deep Sea", "educational", "https://neal.fun/deep-sea/", "Scroll to the bottom of the ocean", ["neal", "ocean", "educational"], 1),
  g("neal-size-of-space", "Size of Space", "educational", "https://neal.fun/size-of-space/", "Explore the scale of the universe", ["neal", "space", "educational"], 1),
  g("neal-earth-reviews", "Earth Reviews", "casual", "https://neal.fun/earth-reviews/", "1-star reviews of Earth landmarks", ["neal", "funny", "reviews"], 1),
  g("neal-life-stats", "Life Stats", "educational", "https://neal.fun/life-stats/", "Stats about your life since birth", ["neal", "stats", "life"], 1),
  g("neal-paint-earth", "Paint the Earth", "casual", "https://neal.fun/paint/", "Collaborative painting on Earth", ["neal", "paint", "creative"], 1),
  g("neal-inflation", "Inflation", "educational", "https://neal.fun/inflation/", "See how inflation affects prices", ["neal", "money", "educational"], 1),
  g("neal-potato", "Potato", "casual", "https://neal.fun/potato/", "Grow potatoes", ["neal", "idle", "potato"], 1),
  g("neal-beat-the-box", "Beat the Box", "puzzle", "https://neal.fun/beat-the-box/", "Beat the box puzzle game", ["neal", "puzzle"], 1),
  g("neal-prime-climb", "Prime Climb", "educational", "https://neal.fun/prime-climb/", "Visual multiplication game", ["neal", "math", "puzzle"], 1),
  g("neal-waving-flag", "Waving Flag", "casual", "https://neal.fun/waving/", "Wave any country flag", ["neal", "flags", "chill"], 1),
  g("neal-universe", "Universe in a Nutshell", "educational", "https://neal.fun/universe/", "Zoom from quarks to the universe", ["neal", "space", "scale"], 1),

  // ── IO Games ────────────────────────────────────────────────────────────
  g("moomoo-io", "MooMoo.io", "io", "https://moomoo.io", "Build a base and fight in an io world", ["io", "build", "multiplayer"], 1),
  g("lordz-io", "Lordz.io", "io", "https://lordz.io", "Build an army and conquer territory", ["io", "strategy", "army"], 1),
  g("splix-io", "Splix.io", "io", "https://splix.io", "Claim territory with your trail", ["io", "territory", "snake"], 1),
  g("hexar-io", "Hexar.io", "io", "https://hexar.io", "Capture hex tiles in this territory game", ["io", "hex", "territory"], 1),
  g("wormate-io", "Wormate.io", "io", "https://wormate.io", "Eat sweets and grow your worm", ["io", "worm", "snake"], 1),
  g("gota-io", "Gota.io", "io", "https://gota.io", "Agar.io-style cell eating game", ["io", "cells", "eat"], 1),
  g("tankar-io", "Tankar.io", "io", "https://tankar.io", "Tank battle io game", ["io", "tanks", "shooter"], 1),
  g("germs-io", "Germs.io", "io", "https://germs.io", "Cell survival io game", ["io", "cells", "survival"], 1),
  g("arras-io", "Arras.io", "io", "https://arras.io", "Diep.io inspired tank shooter", ["io", "tanks", "upgrade"], 1),
  g("foes-io", "Foes.io", "io", "https://foes.io", "Team deathmatch io game", ["io", "shooter", "team"], 1),
  g("zlap-io", "Zlap.io", "io", "https://zlap.io", "Swing your mace to crush enemies", ["io", "mace", "casual"], 1),
  g("snowball-io", "Snowball.io", "io", "https://snowball.io", "Roll snowballs and knock opponents off", ["io", "snowball", "casual"], 1),
  g("thrower-io", "Thrower.io", "io", "https://thrower.io", "Throw weapons to eliminate players", ["io", "throw", "action"], 1),
  g("worm-hunt", "Worm Hunt", "io", "https://wormhunt.io", "Snake-style io worm game", ["io", "worm", "snake"], 1),
  g("skywars-io", "SkyWars.io", "io", "https://skywars.io", "Battle in the sky", ["io", "sky", "battle"], 1),
  g("taming-io", "Taming.io", "io", "https://taming.io", "Tame animals and battle others", ["io", "taming", "survival"], 1),
  g("wanderers-io", "Wanderers.io", "io", "https://wanderers.io", "Lead a tribe in this survival game", ["io", "tribe", "survival"], 1),
  g("territorial-io", "Territorial.io", "io", "https://territorial.io", "Conquer territory in a world map", ["io", "territory", "strategy"], 1),
  g("coordinates-io", "Coordinates.io", "io", "https://coordinates.io", "Geography territory game", ["io", "geography", "strategy"], 1),
  g("warbot-io", "Warbot.io", "io", "https://warbot.io", "Robot battle io game", ["io", "robots", "battle"], 1),
  g("deadshot-io", "Deadshot.io", "io", "https://deadshot.io", "Browser FPS io game", ["io", "fps", "shooter"], 1),
  g("vertix-io", "Vertix.io", "io", "https://vertix.io", "2D shooter io game", ["io", "shooter", "2d"], 1),
  g("surviv-io", "Surviv.io", "io", "https://surviv.io", "2D battle royale", ["io", "battle-royale", "survival"], 1),
  g("pixelwar-io", "PixelWar.io", "io", "https://pixelwar.io", "Pixel battle royale", ["io", "pixel", "battle-royale"], 1),
  g("gulper-io", "Gulper.io", "io", "https://gulper.io", "Eat and grow in this io game", ["io", "eat", "grow"], 1),
  g("crazysnake-io", "CrazySnake.io", "io", "https://crazysnake.io", "Snake io with power-ups", ["io", "snake", "powerups"], 1),
  g("narwhale-io", "Narwhale.io", "io", "https://narwhale.io", "Narwhal jousting io game", ["io", "narwhal", "casual"], 1),
  g("superhex-io", "SuperHex.io", "io", "https://superhex.io", "Hex territory claiming game", ["io", "hex", "territory"], 1),
  g("cellz-io", "Cellz.io", "io", "https://cellz.io", "Cell evolution io game", ["io", "cells", "evolution"], 1),
  g("nightpoint-io", "Nightpoint.io", "io", "https://nightpoint.io", "Zombie survival io game", ["io", "zombie", "survival"], 1),
  g("triep-io", "Triep.io", "io", "https://triep.io", "Triangle shooter io", ["io", "shooter", "triangles"], 1),
  g("miniblox-io", "Miniblox.io", "io", "https://miniblox.io", "Minecraft-style io game", ["io", "minecraft", "blocks"], 1),
  g("repuls-io", "Repuls.io", "io", "https://repuls.io", "3D fps io game", ["io", "fps", "3d"], 1),
  g("kirka-io", "Kirka.io", "io", "https://kirka.io", "FPS io with customization", ["io", "fps", "customize"], 1),
  g("venge-io", "Venge.io", "io", "https://venge.io", "3D FPS io game", ["io", "fps", "3d"], 1),
  g("stabfish-io", "Stabfish.io", "io", "https://stabfish.io", "Stab fish in this io game", ["io", "fish", "casual"], 1),
  g("oceanar-io", "Oceanar.io", "io", "https://oceanar.io", "Ocean creature io game", ["io", "ocean", "creatures"], 1),
  g("kartwars-io", "KartWars.io", "io", "https://kartwars.io", "Kart battle io game", ["io", "karts", "battle"], 1),
  g("bloxd-io", "Bloxd.io", "io", "https://bloxd.io", "Minecraft-style multiplayer", ["io", "minecraft", "multiplayer"], 1),

  // ── Action / Shooting ────────────────────────────────────────────────────
  g("1v1-battle", "1v1 Battle", "action", "https://1v1battle.io", "1v1 battle game", ["action", "battle", "1v1"], 1),
  g("fps-unblocked", "FPS Chess", "action", "https://fpschess.com", "Play chess but first-person-shooter", ["fps", "chess", "unique"], 1),
  g("pixel-gun-apocalypse", "Pixel Gun Apocalypse", "action", "https://www.crazygames.com/game/pixel-gun-apocalypse-5", "Pixel FPS multiplayer", ["fps", "pixel", "multiplayer"], 1),
  g("forward-assault", "Forward Assault", "action", "https://www.crazygames.com/game/forward-assault-remix", "Tactical shooter game", ["fps", "tactical", "shooter"], 1),
  g("gun-mayhem-2", "Gun Mayhem 2", "action", "https://www.crazygames.com/game/gun-mayhem-2-more-mayhem", "Platform shooter party game", ["shooter", "platform", "party"], 1),
  g("masked-forces", "Masked Forces", "action", "https://www.crazygames.com/game/masked-forces", "Multiplayer FPS game", ["fps", "multiplayer", "masked"], 1),
  g("mad-gunz", "Mad GunZ", "action", "https://www.crazygames.com/game/mad-gunz", "Top-down shooter", ["shooter", "top-down", "mad"], 1),
  g("territory-war", "Territory War", "action", "https://www.crazygames.com/game/territory-war-online", "Turn-based territory shooter", ["shooter", "strategy", "turn-based"], 1),
  g("stickman-archer", "Stickman Archer", "action", "https://www.crazygames.com/game/stickman-archer-3", "Stickman archery game", ["stickman", "archery", "action"], 1),
  g("zombie-shooter", "Zombie Shooter", "action", "https://www.crazygames.com/game/zombie-shooter", "Shoot zombies in this survival game", ["zombie", "shooter", "survival"], 1),
  g("warzone-getaway", "Warzone Getaway", "action", "https://www.crazygames.com/game/warzone-getaway", "Shoot enemies and escape", ["action", "shooter", "escape"], 1),
  g("pixel-warfare", "Pixel Warfare", "action", "https://www.crazygames.com/game/pixel-warfare-5", "Pixel art FPS multiplayer", ["fps", "pixel", "multiplayer"], 1),
  g("combat-strike", "Combat Strike", "action", "https://www.crazygames.com/game/combat-strike", "Military FPS browser game", ["fps", "military", "browser"], 1),
  g("zombie-mission", "Zombie Mission", "action", "https://www.crazygames.com/game/zombie-mission", "Co-op zombie missions", ["zombie", "co-op", "action"], 1),
  g("swords-souls", "Swords and Souls", "action", "https://www.crazygames.com/game/swords-and-souls", "Arena RPG with skill training", ["rpg", "arena", "sword"], 1),
  g("castle-wars", "Castle Wars", "action", "https://www.crazygames.com/game/castle-wars-new-era", "Castle siege card game", ["strategy", "castle", "cards"], 1),

  // ── Racing ──────────────────────────────────────────────────────────────
  g("madalin-cars-multiplayer", "Madalin Cars Multiplayer", "racing", "https://www.crazygames.com/game/madalin-cars-multiplayer", "Open world multiplayer car game", ["cars", "multiplayer", "open-world"], 1),
  g("rooftop-snipers", "Rooftop Snipers", "action", "https://www.crazygames.com/game/rooftop-snipers", "2-player rooftop sniping", ["sniper", "2-player", "funny"], 1),
  g("city-car-stunt-4", "City Car Stunt 4", "racing", "https://www.crazygames.com/game/city-car-stunt-4", "Open world car stunt game", ["cars", "stunts", "open-world"], 1),
  g("stickman-boost", "Stickman Boost", "racing", "https://www.crazygames.com/game/stickman-boost-2", "Parkour-style stickman racing", ["stickman", "parkour", "racing"], 1),
  g("offroad-outlaws", "Offroad Outlaws", "racing", "https://www.crazygames.com/game/offroad-outlaws", "Off-road truck racing", ["trucks", "offroad", "racing"], 1),
  g("extreme-car-driving", "Extreme Car Driving", "racing", "https://www.crazygames.com/game/extreme-car-driving-simulator", "Open world car driving sim", ["cars", "simulator", "open-world"], 1),
  g("parking-fury-3d", "Parking Fury 3D", "racing", "https://www.crazygames.com/game/parking-fury-3d", "3D parking challenge", ["cars", "parking", "3d"], 1),
  g("traffic-jam-3d", "Traffic Jam 3D", "racing", "https://www.crazygames.com/game/traffic-jam-3d", "Navigate through traffic in 3D", ["cars", "traffic", "3d"], 1),
  g("mini-racing", "Mini Racing Adventures", "racing", "https://www.crazygames.com/game/mini-racing-adventures", "Side-scrolling mini car racing", ["cars", "mini", "side-scroll"], 1),
  g("road-crash", "Road Crash", "racing", "https://www.crazygames.com/game/road-crash", "Crash into other cars to win", ["cars", "crash", "action"], 1),

  // ── Sports ──────────────────────────────────────────────────────────────
  g("head-soccer", "Head Soccer", "sports", "https://www.crazygames.com/game/head-soccer", "Head-bobbing soccer game", ["soccer", "head", "funny"], 1),
  g("head-football", "Head Football", "sports", "https://www.crazygames.com/game/head-football", "Head football with power-ups", ["football", "head", "2-player"], 1),
  g("stickman-soccer", "Stickman Soccer", "sports", "https://www.crazygames.com/game/stickman-soccer-classic", "Classic stickman soccer", ["soccer", "stickman", "sports"], 1),
  g("basketball-master", "Basketball Master", "sports", "https://www.crazygames.com/game/basketball-master-2", "Flick shots to score baskets", ["basketball", "flick", "casual"], 1),
  g("dunkers-2", "Dunkers 2", "sports", "https://www.crazygames.com/game/dunkers-2", "Physics-based basketball dunk game", ["basketball", "physics", "2-player"], 1),
  g("stick-cricket", "Stick Cricket", "sports", "https://www.crazygames.com/game/stick-cricket", "Simple cricket batting game", ["cricket", "stickman", "sports"], 1),
  g("mini-golf", "Mini Golf", "sports", "https://www.crazygames.com/game/mini-golf-club", "Online mini golf", ["golf", "mini", "casual"], 1),
  g("volleyball-random", "Volleyball Random", "sports", "https://www.crazygames.com/game/volleyball-random", "Wacky physics volleyball", ["volleyball", "physics", "random"], 1),
  g("table-tennis-world-tour", "Table Tennis World Tour", "sports", "https://www.crazygames.com/game/table-tennis-world-tour", "Table tennis tournament", ["ping-pong", "tournament", "sports"], 1),
  g("golf-battle", "Golf Battle", "sports", "https://www.crazygames.com/game/golf-battle", "Multiplayer golf game", ["golf", "multiplayer", "battle"], 1),
  g("bike-racing", "Bike Racing", "sports", "https://www.crazygames.com/game/bike-racing", "Side-scrolling bike race", ["bikes", "racing", "side-scroll"], 1),
  g("stickman-baseball", "Stickman Baseball", "sports", "https://www.crazygames.com/game/stickman-baseball", "Simple baseball game", ["baseball", "stickman", "sports"], 1),

  // ── Puzzle / Strategy ────────────────────────────────────────────────────
  g("2048-original", "2048 Original", "puzzle", "https://gabrielecirulli.github.io/2048/", "The original 2048 game", ["numbers", "puzzle", "classic"], 1),
  g("unblock-me", "Unblock Me", "puzzle", "https://www.crazygames.com/game/unblock-me", "Slide blocks to free the red block", ["blocks", "puzzle", "logic"], 1),
  g("red-ball-4", "Red Ball 4", "puzzle", "https://www.crazygames.com/game/red-ball-4", "Roll the red ball through levels", ["ball", "platform", "puzzle"], 1),
  g("color-fill", "Color Fill 3D", "puzzle", "https://www.crazygames.com/game/color-fill-3d", "Fill the board with your color", ["color", "fill", "casual"], 1),
  g("puzzles-quest", "Puzzle Quest", "puzzle", "https://www.crazygames.com/game/puzzle-quest", "Match-3 RPG puzzle game", ["match-3", "rpg", "puzzle"], 1),
  g("mahjong-dark-dimensions", "Mahjong Dark Dimensions", "puzzle", "https://www.crazygames.com/game/mahjong-dark-dimensions", "3D mahjong puzzle game", ["mahjong", "3d", "puzzle"], 1),
  g("jewel-academy", "Jewel Academy", "puzzle", "https://www.crazygames.com/game/jewel-academy", "Match-3 jewel puzzle", ["match-3", "jewels", "puzzle"], 1),
  g("bubble-shooter", "Bubble Shooter", "puzzle", "https://www.crazygames.com/game/bubble-shooter-hd-2", "Pop bubbles in this classic game", ["bubbles", "shooter", "classic"], 1),
  g("zuma-revenge", "Zuma Revenge", "puzzle", "https://www.crazygames.com/game/zuma-revenge", "Shoot colored balls to clear the path", ["zuma", "balls", "puzzle"], 1),
  g("bob-robber-4", "Bob the Robber 4", "puzzle", "https://www.crazygames.com/game/bob-the-robber-4", "Stealthy heist puzzle game", ["stealth", "puzzle", "heist"], 1),
  g("light-it-up", "Light It Up", "puzzle", "https://www.crazygames.com/game/light-it-up", "Connect light paths puzzle", ["light", "connect", "puzzle"], 1),
  g("jelly-truck", "Jelly Truck", "puzzle", "https://www.crazygames.com/game/jelly-truck", "Drive a jelly truck through levels", ["truck", "jelly", "physics"], 1),
  g("snakebird", "Snakebird", "puzzle", "https://www.crazygames.com/game/snakebird", "Snake meets puzzle platformer", ["snake", "platform", "puzzle"], 1),
  g("numberle", "Numberle", "puzzle", "https://numberle.org", "Wordle but with numbers", ["wordle", "numbers", "daily"], 1),
  g("heardle", "Heardle", "puzzle", "https://www.spotify.com/heardle/", "Guess the song from its intro", ["music", "guess", "daily"], 1),
  g("worldle", "Worldle", "puzzle", "https://worldle.teuteuf.fr", "Guess the country by its shape", ["geography", "wordle", "daily"], 1),
  g("contexto", "Contexto", "puzzle", "https://contexto.me", "Find the secret word by context", ["words", "context", "daily"], 1),
  g("flagle", "Flagle", "puzzle", "https://flagle.io", "Guess the country by its flag", ["flags", "geography", "daily"], 1),
  g("mathler", "Mathler", "puzzle", "https://mathler.com", "Wordle but solve math equations", ["math", "wordle", "daily"], 1),
  g("weddle", "Weddle", "puzzle", "https://www.weddle.app", "NFL player guessing game", ["nfl", "sports", "daily"], 1),
  g("poeltl", "Poeltl", "puzzle", "https://poeltl.dunk.town", "NBA player guessing game", ["nba", "sports", "daily"], 1),
  g("framed", "Framed", "puzzle", "https://framed.wtf", "Guess the movie from a frame", ["movies", "guess", "daily"], 1),
  g("tradle", "Tradle", "puzzle", "https://oec.world/en/tradle/", "Guess country by its exports", ["geography", "trade", "daily"], 1),
  g("immaculate-grid", "Immaculate Grid", "puzzle", "https://www.immaculategrid.com", "Baseball trivia grid game", ["baseball", "trivia", "grid"], 1),
  g("connections", "Connections", "puzzle", "https://www.nytimes.com/games/connections", "Group words that share a connection", ["words", "groups", "daily"], 1),
  g("mini-crossword", "Mini Crossword", "puzzle", "https://www.nytimes.com/crosswords/game/mini", "Quick 5x5 crossword", ["crossword", "words", "daily"], 1),
  g("infinite-craft", "Infinite Craft", "puzzle", "https://neal.fun/infinite-craft/", "Combine elements to create new things", ["craft", "combine", "infinite"], 1),

  // ── Casual / Idle ────────────────────────────────────────────────────────
  g("paperio", "Paper.io 2", "casual", "https://paper-io.com", "Claim territory by drawing trails", ["territory", "io", "casual"], 1),
  g("sprunki", "Sprunki", "casual", "https://sprunki.org", "Music mixing game", ["music", "mixing", "creative"], 1),
  g("incredibox", "Incredibox", "casual", "https://www.incredibox.com/demo/", "Create music by mixing beatboxers", ["music", "creative", "beatbox"], 1),
  g("orteil-idle", "Cookie Clicker 2", "casual", "https://orteil.dashnet.org/experiments/cookie/", "The original cookie clicker", ["idle", "clicker", "cookies"], 1),
  g("adventure-capitalist", "Adventure Capitalist", "casual", "https://www.crazygames.com/game/adventure-capitalist", "Idle business tycoon game", ["idle", "tycoon", "money"], 1),
  g("idle-dice", "Idle Dice", "casual", "https://www.crazygames.com/game/idle-dice", "Roll dice and earn money", ["idle", "dice", "casual"], 1),
  g("gravity-falls-run", "Clicker Heroes", "casual", "https://www.crazygames.com/game/clicker-heroes", "Kill monsters by clicking", ["idle", "clicker", "rpg"], 1),
  g("realm-grinder", "Realm Grinder", "casual", "https://www.kongregate.com/games/DivineGames/realm-grinder", "Idle kingdom building", ["idle", "kingdom", "grinder"], 1),
  g("sandspiel", "Sandspiel", "casual", "https://sandspiel.club", "Falling sand physics simulator", ["sand", "physics", "creative"], 1),
  g("powder-game", "Powder Game", "casual", "https://dan-ball.jp/en/javagame/dust/", "Classic falling sand game", ["sand", "physics", "classic"], 1),
  g("make-it-meme", "Make It Meme", "casual", "https://makememe.org/play", "Multiplayer meme making game", ["memes", "multiplayer", "funny"], 1),
  g("skribbl", "Skribbl.io", "casual", "https://skribbl.io", "Draw and guess multiplayer game", ["draw", "guess", "multiplayer"], 1),
  g("gartic-phone", "Gartic Phone", "casual", "https://garticphone.com", "Telephone game with drawings", ["draw", "funny", "multiplayer"], 1),
  g("skribblio-private", "Drawasaurus", "casual", "https://www.drawasaurus.org", "Draw and guess game", ["draw", "guess", "multiplayer"], 1),
  g("scattergories", "Scattergories", "casual", "https://swellgarfo.com/scattergories/", "Online scattergories game", ["words", "categories", "multiplayer"], 1),
  g("kahoot-it", "Kahoot!", "educational", "https://kahoot.it", "Join live quizzes with a game pin", ["quiz", "educational", "multiplayer"], 1),
  g("blooket", "Blooket", "educational", "https://www.blooket.com", "Gamified quiz platform", ["quiz", "educational", "games"], 1),
  g("quizlet-live", "Quizlet Live", "educational", "https://quizlet.com/live", "Team flashcard game", ["flashcards", "educational", "team"], 1),
  g("geoguessr", "GeoGuessr", "casual", "https://www.geoguessr.com", "Guess where you are in the world", ["geography", "google-maps", "trivia"], 1),
  g("geocle", "Geocle", "casual", "https://geocle.io", "Daily geography guessing game", ["geography", "daily", "guess"], 1),
  g("worldguessr", "WorldGuessr", "casual", "https://worldguessr.com", "Free GeoGuessr alternative", ["geography", "google-maps", "free"], 1),
  g("typeracer", "TypeRacer", "educational", "https://play.typeracer.com", "Race by typing fast", ["typing", "racing", "competitive"], 1),
  g("monkeytype", "Monkeytype", "educational", "https://monkeytype.com", "Clean typing speed test", ["typing", "speed", "clean"], 1),
  g("keybr", "Keybr", "educational", "https://www.keybr.com", "Learn to type with statistics", ["typing", "learn", "statistics"], 1),
  g("10fastfingers", "10FastFingers", "educational", "https://10fastfingers.com", "Typing competition platform", ["typing", "competition", "speed"], 1),
  g("typelit", "TypeLit", "educational", "https://www.typelit.io", "Type famous literature passages", ["typing", "literature", "educational"], 1),

  // ── Adventure / Platform ────────────────────────────────────────────────
  g("vex-6", "Vex 6", "adventure", "https://www.crazygames.com/game/vex-6", "Stickman parkour platformer", ["stickman", "parkour", "platform"], 1),
  g("vex-7", "Vex 7", "adventure", "https://www.crazygames.com/game/vex-7", "Latest Vex parkour game", ["stickman", "parkour", "platform"], 1),
  g("run-4", "Run 4", "adventure", "https://www.crazygames.com/game/run-4", "Run through alien tunnels", ["run", "tunnel", "endless"], 1),
  g("fireboy-watergirl-4", "Fireboy & Watergirl 4", "adventure", "https://www.crazygames.com/game/fireboy-and-watergirl-4-the-crystal-temple", "Crystal temple co-op", ["co-op", "2-player", "crystal"], 1),
  g("fireboy-watergirl-5", "Fireboy & Watergirl 5", "adventure", "https://www.crazygames.com/game/fireboy-and-watergirl-5-elements", "Elements temple co-op", ["co-op", "2-player", "elements"], 1),
  g("electric-man-2", "Electric Man 2", "adventure", "https://www.crazygames.com/game/electric-man-2", "Stickman fighting tournament", ["stickman", "fighting", "tournament"], 1),
  g("the-last-stand", "The Last Stand", "adventure", "https://www.crazygames.com/game/the-last-stand-union-city", "Zombie survival RPG", ["zombie", "survival", "rpg"], 1),
  g("sift-heads", "Sift Heads", "adventure", "https://www.crazygames.com/game/sift-heads-world-act-6", "Hitman action game series", ["hitman", "action", "story"], 1),
  g("burrito-bison", "Burrito Bison", "adventure", "https://www.crazygames.com/game/burrito-bison-launcha-libre", "Launch and bounce for distance", ["launch", "bounce", "upgrade"], 1),
  g("renegade-racing", "Renegade Racing", "adventure", "https://www.crazygames.com/game/renegade-racing", "Race renegade-style with stunts", ["racing", "stunts", "multiplayer"], 1),
  g("age-of-war-2", "Age of War 2", "adventure", "https://www.crazygames.com/game/age-of-war-2", "Evolve and conquer through ages", ["strategy", "war", "evolution"], 1),
  g("super-mario-bros", "Super Mario Flash", "adventure", "https://www.crazygames.com/game/super-mario-flash", "Classic Mario fan game", ["mario", "platform", "classic"], 1),
  g("stick-war", "Stick War", "adventure", "https://www.crazygames.com/game/stick-war", "Stickman army strategy game", ["stickman", "strategy", "army"], 1),
  g("stick-war-legacy", "Stick War: Legacy", "adventure", "https://www.crazygames.com/game/stick-war-legacy", "Expanded stickman war game", ["stickman", "strategy", "legacy"], 1),
  g("the-unfair-platformer", "The Unfair Platformer", "adventure", "https://www.crazygames.com/game/the-unfair-platformer", "Rage-inducing tricky platformer", ["rage", "platform", "tricky"], 1),
  g("neon-rider", "Neon Rider", "adventure", "https://www.crazygames.com/game/neon-rider", "Neon motorcycle platform game", ["neon", "motorcycle", "platform"], 1),
  g("wheely-8", "Wheely 8", "adventure", "https://www.crazygames.com/game/wheely-8-aliens", "Help Wheely the car solve puzzles", ["car", "puzzle", "cute"], 1),
  g("troll-face-quest", "Troll Face Quest", "adventure", "https://www.crazygames.com/game/troll-face-quest-internet-memes", "Troll meme puzzle game", ["troll", "memes", "puzzle"], 1),
  g("escaping-prison", "Escaping the Prison", "adventure", "https://www.crazygames.com/game/escaping-the-prison", "Henry Stickmin escape game", ["stickman", "escape", "choices"], 1),
  g("infiltrating-airship", "Infiltrating the Airship", "adventure", "https://www.crazygames.com/game/infiltrating-the-airship", "Henry Stickmin airship game", ["stickman", "stealth", "choices"], 1),
  g("completing-mission", "Completing the Mission", "adventure", "https://www.crazygames.com/game/completing-the-mission", "Final Henry Stickmin game", ["stickman", "mission", "choices"], 1),
  g("zombocalypse", "Zombocalypse 2", "adventure", "https://www.crazygames.com/game/zombocalypse-2", "Survive zombie hordes", ["zombie", "survival", "action"], 1),
  g("age-of-defense", "Age of Defense", "adventure", "https://www.crazygames.com/game/age-of-defense-4", "Defend your castle through ages", ["defense", "castle", "ages"], 1),

  // ── Minecraft / Building ─────────────────────────────────────────────────
  g("minecraft-classic-web", "Minecraft Classic", "adventure", "https://classic.minecraft.net", "Original browser Minecraft", ["minecraft", "build", "classic"], 1),
  g("eaglercraft", "EaglerCraft", "adventure", "https://eaglercraft.com", "Minecraft 1.5.2 in browser", ["minecraft", "browser", "java"], 1),
  g("minecraft-free-play", "ClassiCube", "adventure", "https://www.classicube.net/server/play/", "Free Minecraft Classic alternative", ["minecraft", "classic", "free"], 1),
  g("sandcraft", "SandCraft", "adventure", "https://www.crazygames.com/game/sandcraft", "Minecraft-like sandbox game", ["minecraft", "sandbox", "build"], 1),
  g("kogama-rocket-league", "KoGaMa", "adventure", "https://www.kogama.com", "User-created 3D worlds", ["3d", "multiplayer", "user-created"], 1),

  // ── Music / Creative ─────────────────────────────────────────────────────
  g("chrome-music-lab", "Chrome Music Lab", "educational", "https://musiclab.chromeexperiments.com", "Visual music experiments by Google", ["music", "google", "creative"], 1),
  g("blob-opera", "Blob Opera", "casual", "https://artsandculture.google.com/experiment/blob-opera/AAHWrq360NcGbw", "Control opera singing blobs", ["music", "opera", "creative"], 1),
  g("patatap", "Patatap", "casual", "https://www.patatap.com", "Press keys to make music and visuals", ["music", "keys", "visual"], 1),
  g("beepbox", "BeepBox", "casual", "https://www.beepbox.co", "Create chiptune music in browser", ["music", "chiptune", "creative"], 1),
  g("flems", "Flems", "casual", "https://flems.io", "Musical visual instrument", ["music", "visual", "instrument"], 1),
  g("draw-a-stickman", "Draw a Stickman", "casual", "https://www.drawastickman.com", "Draw your hero and play the game", ["draw", "stickman", "creative"], 1),
  g("aggie-io", "Aggie.io", "casual", "https://aggie.io", "Collaborative drawing canvas", ["draw", "collaborative", "art"], 1),
  g("ttrpg-one", "One Page Dungeon", "casual", "https://watabou.itch.io/one-page-dungeon", "Procedural dungeon generator", ["rpg", "dungeon", "generator"], 1),

  // ── Math / Educational disguise ──────────────────────────────────────────
  g("prodigy-math", "Prodigy Math", "educational", "https://www.prodigygame.com/main-en/", "RPG math game for students", ["math", "rpg", "educational"], 1),
  g("coolmath-run3", "Run 3 (CoolMath)", "educational", "https://www.coolmathgames.com/0-run-3", "Run 3 on CoolMath", ["run", "tunnel", "coolmath"], 1),
  g("coolmath-snake", "Snake (CoolMath)", "educational", "https://www.coolmathgames.com/0-snake", "Snake on CoolMath Games", ["snake", "classic", "coolmath"], 1),
  g("coolmath-chess", "Chess (CoolMath)", "educational", "https://www.coolmathgames.com/0-chess", "Chess on CoolMath", ["chess", "classic", "coolmath"], 1),
  g("coolmath-moto-x3m", "Moto X3M (CoolMath)", "educational", "https://www.coolmathgames.com/0-moto-x3m", "Moto X3M on CoolMath", ["bikes", "stunts", "coolmath"], 1),
  g("gimkit", "Gimkit", "educational", "https://www.gimkit.com/join", "Join a live Gimkit quiz", ["quiz", "educational", "live"], 1),
  g("blooket-join", "Blooket Join", "educational", "https://dashboard.blooket.com/join", "Join a Blooket game", ["quiz", "educational", "blooket"], 1),
  g("kahoot-join", "Kahoot Join", "educational", "https://kahoot.it/#/", "Join a Kahoot quiz", ["quiz", "educational", "kahoot"], 1),
  g("quizziz", "Quizizz", "educational", "https://quizizz.com/join", "Join a Quizizz game", ["quiz", "educational", "quizizz"], 1),

  // ── More Popular Titles ──────────────────────────────────────────────────
  g("getaway-shootout-2", "Getaway Shootout", "action", "https://www.crazygames.com/game/getaway-shootout", "Race and shoot to escape", ["shooter", "racing", "2-player"], 1),
  g("parkour-block-3d", "Parkour Block 3D", "adventure", "https://www.crazygames.com/game/parkour-block-5-3d", "3D Minecraft-style parkour", ["minecraft", "parkour", "3d"], 1),
  g("monkey-mart", "Monkey Mart", "casual", "https://www.crazygames.com/game/monkey-mart", "Run a supermarket as a monkey", ["monkey", "supermarket", "idle"], 1),
  g("house-of-hazards", "House of Hazards", "casual", "https://www.crazygames.com/game/house-of-hazards", "Multiplayer house obstacle game", ["multiplayer", "obstacles", "funny"], 1),
  g("only-up-parkour", "Only Up Parkour", "adventure", "https://www.crazygames.com/game/only-up", "Climb up and don't fall", ["parkour", "climb", "rage"], 1),
  g("squid-game", "Squid Game", "action", "https://www.crazygames.com/game/squid-game-456", "Squid Game survival challenges", ["squid-game", "survival", "action"], 1),
  g("poppy-playtime", "Poppy Playtime Online", "adventure", "https://www.crazygames.com/game/poppy-playtime-chapter-2", "Poppy Playtime browser game", ["horror", "poppy", "adventure"], 1),
  g("among-us-online-free", "Among Us Online", "casual", "https://www.crazygames.com/game/among-us-online-free", "Among Us in browser", ["among-us", "multiplayer", "social"], 1),
  g("fall-guys-free", "Fall Beans Ultimate", "casual", "https://www.crazygames.com/game/fall-beans-ultimate-knockout", "Fall Guys style knockouts", ["fall-guys", "knockout", "casual"], 1),
  g("friday-night-funkin-online", "FNF Online", "action", "https://www.crazygames.com/game/friday-night-funkin", "FNF in browser", ["fnf", "rhythm", "music"], 1),
  g("stumble-guys", "Stumble Guys Online", "casual", "https://www.crazygames.com/game/stumble-guys-online", "Stumble Guys browser version", ["stumble", "multiplayer", "casual"], 1),
  g("baldi-basics", "Baldi's Basics", "adventure", "https://www.crazygames.com/game/baldis-basics", "Avoid Baldi in school", ["horror", "school", "avoid"], 1),
  g("granny-online", "Granny Online", "adventure", "https://www.crazygames.com/game/granny", "Escape from Granny's house", ["horror", "escape", "granny"], 1),
  g("rocket-league-sideswipe", "Rocket Soccer Derby", "sports", "https://www.crazygames.com/game/rocket-soccer-derby", "Rocket League-style soccer", ["rocket", "soccer", "cars"], 1),
  g("chess-rush", "Chess Rush", "puzzle", "https://www.crazygames.com/game/chess-rush", "Auto chess battle game", ["chess", "auto", "battle"], 1),
  g("tower-defense-king", "Tower Defense King", "strategy", "https://www.crazygames.com/game/tower-defense-king", "Classic tower defense game", ["tower-defense", "strategy", "classic"], 1),
  g("btd5-web", "Bloons TD 5", "strategy", "https://www.crazygames.com/game/bloons-tower-defense-5", "Bloons Tower Defense 5", ["bloons", "tower-defense", "strategy"], 1),
  g("plants-vs-zombies", "Plants vs Zombies", "strategy", "https://www.crazygames.com/game/plants-vs-zombies", "Classic PvZ tower defense", ["plants", "zombies", "tower-defense"], 1),
  g("kingdom-rush", "Kingdom Rush", "strategy", "https://www.crazygames.com/game/kingdom-rush", "Epic tower defense RPG", ["tower-defense", "rpg", "kingdom"], 1),
  g("gemcraft", "GemCraft", "strategy", "https://www.crazygames.com/game/gemcraft-frostborn-wrath", "Gem-based tower defense", ["gems", "tower-defense", "strategy"], 1),
  g("creeper-world-ite", "Creeper World ITE", "strategy", "https://www.crazygames.com/game/creeper-world-ite", "Hold back the creeper fluid", ["strategy", "creeper", "unique"], 1),
  g("rogue-survivor", "Rogue Survivor", "strategy", "https://www.crazygames.com/game/rogue-survivor-reborn", "Zombie survival roguelike", ["roguelike", "zombie", "survival"], 1),
  g("swords-souls-neverseen", "Swords & Souls: Neverseen", "adventure", "https://www.crazygames.com/game/swords-and-souls-neverseen", "Arena RPG sequel", ["rpg", "arena", "sword"], 1),
  g("dragon-ball-fighting", "Dragon Ball Fighting", "action", "https://www.crazygames.com/game/dragon-ball-fighting", "DBZ-style fighting game", ["dbz", "fighting", "anime"], 1),
  g("naruto-fighting", "Naruto Fighting", "action", "https://www.crazygames.com/game/naruto-fighting", "Naruto browser fighting game", ["naruto", "fighting", "anime"], 1),
  g("one-piece-game", "One Piece Fighting", "action", "https://www.crazygames.com/game/one-piece-fighting-game", "One Piece browser game", ["one-piece", "fighting", "anime"], 1),
  g("anime-fighting-sim", "Anime Fighting Simulator", "action", "https://www.roblox.com/games/6460049385", "Roblox anime fighting game", ["roblox", "anime", "fighting"], 1),
  g("mini-militia", "Mini Militia", "action", "https://www.crazygames.com/game/mini-militia-doodle-army-2", "2D multiplayer shooter", ["shooter", "2d", "multiplayer"], 1),
  g("battle-arena", "Battle Arena", "action", "https://www.crazygames.com/game/battle-arena", "Arena combat game", ["arena", "combat", "action"], 1),
  g("stickman-fighting-3d", "Stickman Fighter 3D", "action", "https://www.crazygames.com/game/stickman-fighter-3d", "3D stickman fighting game", ["stickman", "fighting", "3d"], 1),
  g("gun-spin", "Gun Spin", "casual", "https://www.crazygames.com/game/gun-spin", "Spin your gun to fly", ["gun", "spin", "casual"], 1),
  g("draw-climber", "Draw Climber", "casual", "https://www.crazygames.com/game/draw-climber", "Draw legs to climb obstacles", ["draw", "climb", "casual"], 1),
  g("paper-fold", "Paper Fold", "puzzle", "https://www.crazygames.com/game/paper-fold", "Fold paper to match the shape", ["paper", "fold", "puzzle"], 1),
  g("brain-test", "Brain Test", "puzzle", "https://www.crazygames.com/game/brain-test", "Tricky brain teaser puzzles", ["brain", "tricky", "puzzle"], 1),
  g("who-is", "Who Is?", "puzzle", "https://www.crazygames.com/game/who-is", "Find the odd one out", ["find", "odd", "puzzle"], 1),
  g("dop-draw-one-part", "DOP Draw", "puzzle", "https://www.crazygames.com/game/dop-draw-one-part", "Draw to solve the puzzle", ["draw", "solve", "puzzle"], 1),
  g("murder", "Murder", "casual", "https://www.crazygames.com/game/murder", "Find the murderer party game", ["murder", "party", "mystery"], 1),
  g("betrayal-io", "Betrayal.io", "casual", "https://betrayal.io", "Social deduction browser game", ["social-deduction", "io", "multiplayer"], 1),
  g("codenames-online", "Codenames", "casual", "https://codenames.game", "Spy codenames party game", ["party", "words", "spy"], 1),
  g("jackbox-drawful", "Drawful 2 Free", "casual", "https://www.jackboxgames.com/drawful-two/", "Draw and lie party game", ["draw", "party", "funny"], 1),
  g("sketchful-io", "Sketchful.io", "casual", "https://sketchful.io", "Draw and guess multiplayer", ["draw", "guess", "multiplayer"], 1),
  g("psych", "Psych!", "casual", "https://psych.fandom.com/wiki/Psych!", "Bluff your friends trivia game", ["trivia", "bluff", "party"], 1),
  g("wiki-game", "The Wiki Game", "casual", "https://www.thewikigame.com", "Race through Wikipedia links", ["wikipedia", "race", "links"], 1),
  g("sporcle", "Sporcle", "educational", "https://www.sporcle.com", "Thousands of free trivia quizzes", ["trivia", "quiz", "educational"], 1),
  g("jetpunk", "JetPunk", "educational", "https://www.jetpunk.com", "Geography and trivia quizzes", ["trivia", "geography", "quiz"], 1),
  g("pictionaryman", "PictionaryMan", "casual", "https://pictionaryman.com", "Online Pictionary game", ["draw", "guess", "pictionary"], 1),
];

const toAdd = MEGA_GAMES.filter(g => !existingIds.has(g.id));
const merged = [...existing, ...toAdd];
fs.writeFileSync(GAMES_JSON, JSON.stringify(merged, null, 2));
console.log(`\n✅ Added ${toAdd.length} new games — total now ${merged.length}\n`);
toAdd.slice(0, 20).forEach(g => console.log(`  + ${g.name}`));
if (toAdd.length > 20) console.log(`  ... and ${toAdd.length - 20} more`);
