const fs = require('fs');
const path = require('path');

const PUBLIC_DIR = path.join(__dirname, '..', 'public');
const NM = path.join(__dirname, '..', 'node_modules');

function copyStaticAssets() {
  // ── Ultraviolet: copy dist files to /frog/ ──
  const uvDist = path.join(NM, '@titaniumnetwork-dev', 'ultraviolet', 'dist');
  const uvDest = path.join(PUBLIC_DIR, 'frog');
  if (fs.existsSync(uvDist)) {
    fs.cpSync(uvDist, uvDest, { recursive: true, force: true });
    console.log('[setup-proxy] Copied Ultraviolet dist assets to /frog/');

    // Create UV config that matches our /frog/ prefix
    const uvConfig = `// STRATO UV Config — auto-generated by setup-proxy
self.__uv$config = {
  prefix: '/frog/',
  bare: '/bare/',
  encodeUrl: Ultraviolet.codec.xor.encode,
  decodeUrl: Ultraviolet.codec.xor.decode,
  handler: '/frog/uv.handler.js',
  bundle: '/frog/uv.bundle.js',
  config: '/frog/uv.config.js',
  sw: '/frog/uv.sw.js',
};
`;
    fs.writeFileSync(path.join(uvDest, 'uv.config.js'), uvConfig);
    console.log('[setup-proxy] Created uv.config.js with /frog/ prefix');
  } else {
    console.warn('[setup-proxy] Ultraviolet dist directory not found — skipping UV asset copy');
  }

  // ── Scramjet: copy dist files to /scramjet/ ──
  const sjDist = path.join(NM, '@mercuryworkshop', 'scramjet', 'dist');
  const sjDest = path.join(PUBLIC_DIR, 'scramjet');
  if (fs.existsSync(sjDist)) {
    fs.cpSync(sjDist, sjDest, { recursive: true, force: true });
    console.log('[setup-proxy] Copied Scramjet dist assets to /scramjet/');

    // Create Scramjet service worker that imports the bundle
    // Use importScripts for classic SW (module SWs have limited browser support)
    const sjSw = `// STRATO Scramjet Service Worker — auto-generated by setup-proxy
try { importScripts('/scramjet/scramjet.bundle.js'); } catch(e) { console.warn('[STRATO/SJ] Failed to load scramjet bundle:', e); }
`;
    fs.writeFileSync(path.join(sjDest, 'sw.js'), sjSw);
    console.log('[setup-proxy] Created scramjet/sw.js');
  } else {
    console.warn('[setup-proxy] Scramjet dist directory not found — skipping Scramjet asset copy');
  }

  // ── Epoxy TLS worker ──
  const epoxyPaths = [
    path.join(NM, '@mercuryworkshop', 'epoxy-tls', 'full', 'epoxy-bundled.js'),
    path.join(NM, '@mercuryworkshop', 'epoxy-tls', 'dist', 'index.js'),
  ];
  const epoxyDest = path.join(PUBLIC_DIR, 'epoxy', 'index.js');
  let epoxyCopied = false;
  for (const epoxySource of epoxyPaths) {
    if (fs.existsSync(epoxySource)) {
      fs.mkdirSync(path.dirname(epoxyDest), { recursive: true });
      fs.copyFileSync(epoxySource, epoxyDest);
      console.log('[setup-proxy] Copied Epoxy TLS worker from', path.basename(path.dirname(epoxySource)));
      epoxyCopied = true;
      break;
    }
  }
  if (!epoxyCopied) {
    console.warn('[setup-proxy] Epoxy TLS not found — skipping');
  }

  // ── Bare Mux worker ──
  const bareMuxPaths = [
    path.join(NM, '@mercuryworkshop', 'bare-mux', 'dist', 'index.js'),
    path.join(NM, '@mercuryworkshop', 'bare-mux', 'dist', 'index.mjs'),
  ];
  const bareMuxDest = path.join(PUBLIC_DIR, 'bare-mux', 'index.js');
  let bareMuxCopied = false;
  for (const bareMuxSource of bareMuxPaths) {
    if (fs.existsSync(bareMuxSource)) {
      fs.mkdirSync(path.dirname(bareMuxDest), { recursive: true });
      fs.copyFileSync(bareMuxSource, bareMuxDest);
      console.log('[setup-proxy] Copied Bare Mux worker');
      bareMuxCopied = true;
      break;
    }
  }
  if (!bareMuxCopied) {
    console.warn('[setup-proxy] Bare Mux dist not found — skipping');
  }

  console.log('[setup-proxy] Asset copy complete');
}

copyStaticAssets();
