const fs = require('fs');
const path = require('path');

const PUBLIC_DIR = path.join(__dirname, '..', 'public');
const NM = path.join(__dirname, '..', 'node_modules');

function copyStaticAssets() {
  // ── Ultraviolet: copy dist files to /frog/ ──
  const uvDist = path.join(NM, '@titaniumnetwork-dev', 'ultraviolet', 'dist');
  const uvDest = path.join(PUBLIC_DIR, 'frog');
  if (fs.existsSync(uvDist)) {
    fs.cpSync(uvDist, uvDest, { recursive: true, force: true });
    console.log('[setup-proxy] Copied Ultraviolet dist assets to /frog/');

    // Create UV config that matches our /frog/ prefix
    const uvConfig = `// STRATO UV Config — auto-generated by setup-proxy
self.__uv$config = {
  prefix: '/frog/',
  bare: '/bare/',
  encodeUrl: Ultraviolet.codec.xor.encode,
  decodeUrl: Ultraviolet.codec.xor.decode,
  handler: '/frog/uv.handler.js',
  bundle: '/frog/uv.bundle.js',
  config: '/frog/uv.config.js',
  sw: '/frog/uv.sw.js',
};
`;
    fs.writeFileSync(path.join(uvDest, 'uv.config.js'), uvConfig);
    console.log('[setup-proxy] Created uv.config.js with /frog/ prefix');

    // Patch sw.js to ensure self.Ultraviolet is set before uv.sw.js loads
    const swPath = require('path').join(uvDest, 'sw.js');
    const patchedSw = `importScripts('uv.bundle.js');
if (typeof self.Ultraviolet === 'undefined' && typeof Ultraviolet !== 'undefined') {
    self.Ultraviolet = Ultraviolet;
}
importScripts('uv.config.js');
importScripts(__uv$config.sw || 'uv.sw.js');
const uv = new UVServiceWorker();
async function handleRequest(event) {
    if (uv.route(event)) return await uv.fetch(event);
    return await fetch(event.request);
}
self.addEventListener('fetch', (event) => {
    event.respondWith(handleRequest(event));
});`;
    require('fs').writeFileSync(swPath, patchedSw);
    console.log('[setup-proxy] Patched sw.js with Ultraviolet safety check');

  } else {
    console.warn('[setup-proxy] Ultraviolet dist directory not found — skipping UV asset copy');
  }

  // ── Scramjet: copy dist files to /scramjet/ ──
  const sjDist = path.join(NM, '@mercuryworkshop', 'scramjet', 'dist');
  const sjDest = path.join(PUBLIC_DIR, 'scramjet');
  if (fs.existsSync(sjDist)) {
    fs.cpSync(sjDist, sjDest, { recursive: true, force: true });
    console.log('[setup-proxy] Copied Scramjet dist assets to /scramjet/');

    // Create Scramjet service worker
    // Scramjet v1+ uses ESM exports in scramjet.bundle.js
    // The SW must be registered as {type: 'module'} for ESM imports to work
    const sjSw = `// STRATO Scramjet Service Worker — auto-generated by setup-proxy
// Scramjet v1+ uses ESM exports — registered as module-type SW
import './scramjet.bundle.js';
`;
    fs.writeFileSync(path.join(sjDest, 'sw.js'), sjSw);
    console.log('[setup-proxy] Created scramjet/sw.js (ESM module type)');

    // Create classic SW fallback for browsers that don't support module-type SWs
    // Uses importScripts with the IIFE bundle (scramjet.all.js) instead of ESM
    const sjSwClassic = `// STRATO Scramjet Service Worker (Classic) — auto-generated by setup-proxy
// Uses importScripts for browsers that don't support module-type SWs
try {
  importScripts('./scramjet.all.js');
} catch (err) {
  console.error('[STRATO] Scramjet classic SW importScripts failed:', err.message);
}
`;
    fs.writeFileSync(path.join(sjDest, 'sw.classic.js'), sjSwClassic);
    console.log('[setup-proxy] Created scramjet/sw.classic.js (classic fallback)');
  } else {
    console.warn('[setup-proxy] Scramjet dist directory not found — skipping Scramjet asset copy');
  }

  // ── Epoxy TLS worker ──
  const epoxyTransportDir = path.join(NM, '@mercuryworkshop', 'epoxy-transport', 'dist');
  const epoxyDestDir = path.join(PUBLIC_DIR, 'epoxy');
  if (fs.existsSync(path.join(epoxyTransportDir, 'index.mjs'))) {
    fs.mkdirSync(epoxyDestDir, { recursive: true });
    fs.copyFileSync(path.join(epoxyTransportDir, 'index.mjs'), path.join(epoxyDestDir, 'index.mjs'));
    if (fs.existsSync(path.join(epoxyTransportDir, 'index.js'))) {
      fs.copyFileSync(path.join(epoxyTransportDir, 'index.js'), path.join(epoxyDestDir, 'index.js'));
    }
    console.log('[setup-proxy] Copied Epoxy BareMux transport to /epoxy/');
  } else {
    console.warn('[setup-proxy] Epoxy BareMux transport not found; skipping');
  }
  const unusedEpoxyPaths = [
    path.join(NM, '@mercuryworkshop', 'epoxy-tls', 'full', 'epoxy-bundled.js'),
    path.join(NM, '@mercuryworkshop', 'epoxy-tls', 'dist', 'index.js'),
  ];
  const epoxyDest = path.join(PUBLIC_DIR, 'epoxy', 'index.js');
  let epoxyCopied = false;
  for (const epoxySource of []) {
    if (fs.existsSync(epoxySource)) {
      fs.mkdirSync(path.dirname(epoxyDest), { recursive: true });
      fs.copyFileSync(epoxySource, epoxyDest);
      console.log('[setup-proxy] Copied Epoxy TLS worker from', path.basename(path.dirname(epoxySource)));
      epoxyCopied = true;
      break;
    }
  }
  if (false && !epoxyCopied) {
    console.warn('[setup-proxy] Epoxy TLS not found — skipping');
  }

  // ── Bare Mux worker ──
  const bareMuxPaths = [
    path.join(NM, '@mercuryworkshop', 'bare-mux', 'dist', 'index.js'),
    path.join(NM, '@mercuryworkshop', 'bare-mux', 'dist', 'index.mjs'),
  ];
  const bareMuxDest = path.join(PUBLIC_DIR, 'bare-mux', 'index.js');
  let bareMuxCopied = false;
  for (const bareMuxSource of bareMuxPaths) {
    if (fs.existsSync(bareMuxSource)) {
      fs.mkdirSync(path.dirname(bareMuxDest), { recursive: true });
      fs.copyFileSync(bareMuxSource, bareMuxDest);
      console.log('[setup-proxy] Copied Bare Mux worker');
      bareMuxCopied = true;
      break;
    }
  }
  if (!bareMuxCopied) {
    console.warn('[setup-proxy] Bare Mux dist not found — skipping');
  }

  // ── Patch bare-mux: fix infinite retry loop ──
  const bareMuxWorkerSource = path.join(NM, '@mercuryworkshop', 'bare-mux', 'dist', 'worker.js');
  const bareMuxWorkerDest = path.join(PUBLIC_DIR, 'bare-mux', 'worker.js');
  if (fs.existsSync(bareMuxWorkerSource)) {
    fs.copyFileSync(bareMuxWorkerSource, bareMuxWorkerDest);
    console.log('[setup-proxy] Copied Bare Mux SharedWorker');
  }

  // The bare-mux library has an infinite retry in its SharedWorker MessagePort
  // acquisition function. This patch adds a max retry count (5) and proper
  // error handling instead of recursing forever.
  if (fs.existsSync(bareMuxDest)) {
    let bareMuxCode = fs.readFileSync(bareMuxDest, 'utf8');

    // Patch 1: Add retry counter to the recursive function `c()`
    // Original: async function c(){...await c()}
    // Patched:  async function c(n=0){if(n>=5)throw ...;...await c(n+1)}
    bareMuxCode = bareMuxCode.replace(
      /async function c\(\)\{/,
      'async function c(n=0){if(n>=5)throw console.error("bare-mux: max retries (5) exceeded getting SharedWorker MessagePort"),new Error("Max retries exceeded getting SharedWorker MessagePort");'
    );
    bareMuxCode = bareMuxCode.replace(
      /console\.warn\("bare-mux: failed to get a bare-mux SharedWorker MessagePort within 1s, retrying"\),await c\(\)/,
      'console.warn("bare-mux: failed to get a bare-mux SharedWorker MessagePort within 1s, retrying ("+(n+1)+"/5)"),await c(n+1)'
    );

    // Patch 2: Add retry counter to sendMessage reconnect
    // Original: async sendMessage(e,t){...this.createChannel(),await this.sendMessage(e,t)}
    // Patched:  async sendMessage(e,t,_r=0){if(_r>=3)throw ...;...await this.sendMessage(e,t,_r+1)}
    bareMuxCode = bareMuxCode.replace(
      /async sendMessage\(e,t\)\{/,
      'async sendMessage(e,t,_r=0){'
    );
    bareMuxCode = bareMuxCode.replace(
      /console\.warn\("bare-mux: Failed to get a ping response from the worker within 1\.5s\. Assuming port is dead\."\),this\.createChannel\(\),await this\.sendMessage\(e,t\)/,
      'console.warn("bare-mux: Failed to get a ping response from the worker within 1.5s. Assuming port is dead. Retry "+(_r+1)+"/3"),this.createChannel(),await this.sendMessage(e,t,_r+1)'
    );
    // Add retry limit check at start of sendMessage catch block
    bareMuxCode = bareMuxCode.replace(
      'this.port instanceof Promise&&(this.port=await this.port);try{await i(this.port)}catch{return console.warn',
      'this.port instanceof Promise&&(this.port=await this.port);try{await i(this.port)}catch{if(_r>=3)throw console.error("bare-mux: Failed to reconnect after 3 attempts"),new Error("Failed to reconnect to SharedWorker");return console.warn'
    );

    fs.writeFileSync(bareMuxDest, bareMuxCode);
    console.log('[setup-proxy] Patched bare-mux: added retry limits (5 for SW, 3 for reconnect)');
  }

  console.log('[setup-proxy] Asset copy complete');
}

copyStaticAssets();
